### ISSUE TITLE
Conflict with Auto ban extension

### ISSUE THREAD

**Issue by Galixte** [rxu/advanced_warnings#26]
Hi @rxu,

in ACP the setting enter in conflict with ACP settings from this extension: https://github.com/satanasov/autoban.

The displaying of the settings for Auto Ban extension are not displayed.

**Comment by lavigor** [comment]
It is because Advanced Warnings extension hides the `warnings_expire_days` configuration setting.
@Galixte, try the following: [here](https://github.com/rxu/advanced_warnings/blob/master/event/listener.php#L84) replace `'add_acp_config'` with `array('add_acp_config', -2)`.

**Comment by lavigor** [comment]
Hi, @Galixte.
Please try the fix in PR #27.

**Comment by Galixte** [comment]
It’s OK you can merge this PR.
